name: GitVersion Tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Tag with GitVersion
        id: gitversion
        uses: michielvha/gitversion-tag-action@main
        with:
          configFilePath: 'gitversion.yml'
